java_binary(
    name = "java-harness",
    main_class = "com.lyft.pgv.validation.JavaHarness",
    visibility = ["//tests/harness:__subpackages__"],
    runtime_deps = [
        "//java/pgv-java-validation/src/main/java/com/lnnujxxy/pgv/validation:java_harness",
    ],
)
